typography_spectrum: 0.793220326770097
color:
  brandStrength: 0.676950013032183
  lightness: 0.46297909668646753
  saturation: 0.47979083517566323
  rhythmicContrast: 0.5987114482559264
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.17641499848105013
author:
  name: Paula Verdicchio
  email: paulaverdicchio@gmail.com
  url: 'http://paulaverdicchio.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3bd5df26-31ce-4fc5-bf12-644490e10c2c.png
name: Soul Centered
favicon: null
title: Soul Centered
description: 'music, art, metaphysics'
